sonar.projectKey=AndreyMasyukevich_First-repositori
sonar.organization=AndreyMasyukevich
sonar.projectName=First-repositori
sonar.projectVersion=1.0

# Указываем, где лежат исходники
sonar.sources = https://sonarcloud.io/organizations/andreymasyukevich4-spec/projects
# Исключаем мусорные файлы, чтобы Сонар их не проверял
sonar.exclusions=**/*.exe,**/*.obj,**/*.pdb,**/*.ilk

# Для C++ обязательно указываем стандарт языка
sonar.cfamily.compile.commands=compile_commands.json